name: test
project_name: sray


DAT:
    final_output: False
    down_projs: True
    img_size: [80,60]
    patch_size: 1
    num_classes: 21
    in_dim: 32


    expansion: 4
    dim_stem: 96
    dims: [96, 192, 384, 768]
    depths: [2, 4, 18, 2]
    stage_spec: [[N, D], [N, D, N, D], [N, D, N, D, N, D, N, D, N, D, N, D, N, D, N, D, N, D], [D, D]]
    heads: [3, 6, 12, 24]
    window_sizes: [7, 7, 7, 7]
    groups: [1, 2, 3, 6]
    use_pes: [True, True, True, True]
    dwc_pes: [False, False, False, False]
    strides: [8, 4, 2, 1]
    offset_range_factor: [-1, -1, -1, -1]
    no_offs: [False, False, False, False]
    fixed_pes: [False, False, False, False]
    use_dwc_mlps: [True, True, True, True]
    use_lpus: [True, True, True, True]
    use_conv_patches: False
    ksizes: [9, 7, 5, 3]
    nat_ksizes: [7, 7, 7, 7]
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.4