name: test
project_name: sray

# network
use_tpvformer: false
init_net_type: depth
use_hierarchical_sampling: false
use_depth_loss: false
dist_decoder_cfg:
  use_vis: true
fine_dist_decoder_cfg:
  use_vis: true

render_label: true
num_classes: 20
ignore_label: 20
agg_net_cfg: {
  network_name: CRANet_CV_IBR_v2,
  label_hidden: [16],
  num_classes: 20,
  use_ptrans: true,
  ptrans_first: false,
  sem_only: true,
  color_cal_type: feat_pred, # 
  n_samples: 96,
}


# loss
loss: [render, semantic_v2, ref_depth, depth]
render_loss_scale: 0.75
semantic_loss_scale: 0.25
ref_depth_scale: 0.1
label_loss_scale: 0.5
depth_loss_scale: 0.1
semantic_loss_2d_scale: 0.
val_metric: [psnr_ssim, vis_img, iou, vis_sem]
key_metric_name: miou
use_dr_loss: false
use_dr_fine_loss: false
use_nr_fine_loss: false

# lr
# load_pretrain: data/model/neuray_gen_depth/model_best.pth
total_step: 600000
val_interval: 5000
save_interval: 5000
lr_type: exp_decay
optimizer_type: adam
max_grad_norm: 10
lr_cfg:
  scale_new: 1.0
  lr_init: 1.0e-4
  decay_step: 5000
  decay_rate: 0.2
  lr_min: 1.0e-6
  optim_args: {weight_decay: 1.0e-6}

# dataset
train_dataset_cfg:
  resolution_type: lr
  type2sample_weights: {scannet: 1}
  train_database_types: ['scannet']
  aug_pixel_center_sample: true
  train_ray_num:  1024 #32*32*N_patch
  use_patch: false
  patch_size: [32,32]
  num_geo_src_views: 8
  use_select_working_views_v2: true
  N1: 3
  N2: 5
val_set_list: configs/scannetv2_val_split.txt

semantic_color_map: [
  [174, 199, 232],  # wall
  [152, 223, 138],  # floor
  [31, 119, 180],   # cabinet
  [255, 187, 120],  # bed
  [188, 189, 34],   # chair
  [140, 86, 75],    # sofa
  [255, 152, 150],  # table
  [214, 39, 40],    # door
  [197, 176, 213],  # window
  [148, 103, 189],  # bookshelf
  [196, 156, 148],  # picture
  [23, 190, 207],   # counter
  [247, 182, 210],  # desk
  [219, 219, 141],  # curtain
  [255, 127, 14],   # refrigerator
  [91, 163, 138],   # shower curtain
  [44, 160, 44],    # toilet
  [112, 128, 144],  # sink
  [227, 119, 194],  # bathtub
  [82, 84, 163],    # otherfurn
  [248, 166, 116],  # invalid
]

# aabb : [[-1, -1, -1], [1, 1, 1]],
# near : 0.05,
# far : 2.5,
voxel_size : [.16, .16, .2]
n_voxels : [40, 40, 16]
aabb : [[-2.7, -2.7, -0.78], [3.7, 3.7, 1.78]]
origin : [.0, .0, .5]


M2F:
  config_file : '/home/chengshun.wang/pjs/mmsegmentation/m2f_pt/mask2former_r50_scannet_2d_240x320_pretrain.py'
  checkpoint_file : '/home/chengshun.wang/pjs/mmsegmentation/m2f_pt/best_mIoU_iter_85000.pth'

# geonerf
# nb_views: 5

# DAT:
#     final_output: False
#     down_projs: True
#     img_size: [80,60]
#     patch_size: 1
#     num_classes: 21
#     in_dim: 32
#     expansion: 4
#     dim_stem: 96
#     dims: [96, 192]
#     depths: [2, 4, 18, 2]
#     stage_spec: [[N, D], [N, D, N, D], ]
#     heads: [3, 6, 12, 24]
#     window_sizes: [7, 7, 7, 7]
#     groups: [1, 2, 3, 6]
#     use_pes: [True, True, True, True]
#     dwc_pes: [False, False, False, False]
#     strides: [8, 4, 2, 1]
#     offset_range_factor: [-1, -1, -1, -1]
#     no_offs: [False, False, False, False]
#     fixed_pes: [False, False, False, False]
#     use_dwc_mlps: [True, True, True, True]
#     use_lpus: [True, True, True, True]
#     use_conv_patches: False
#     ksizes: [9, 7, 5, 3]
#     nat_ksizes: [7, 7, 7, 7]
#     drop_rate: 0.0
#     attn_drop_rate: 0.0
#     drop_path_rate: 0.4